### ISSUE TITLE
Null pointer dereference and segfault in PycRef

### ISSUE THREAD

**Issue by geeknik** [zrax/pycdc#128]
Compiled with `-fsanitize=address,undefined` via AFL on Debian 8 x64.

./pycdc [test000.pyc](https://github.com/zrax/pycdc/files/1110261/test000.pyc.gz)
```
CreateObject: Got unsupported type 0x7F
# Source Generated with Decompyle++
# File: test000.pyc (Python 1.5)

ASAN:SIGSEGV
=================================================================
==28496==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000028 (pc 0x000000418b3c sp 0x7ffd0ae66ba0 bp 0x7ffd0ae6a560 T0)
    #0 0x418b3b in PycRef /root/pycdc/pyc_object.h:15
    #1 0x418b3b in PycCode::code() const /root/pycdc/pyc_code.h:41
    #2 0x418b3b in BuildFromCode(PycRef<PycCode>, PycModule*) /root/pycdc/ASTree.cpp:27
    #3 0x547606 in decompyle(PycRef<PycCode>, PycModule*) /root/pycdc/ASTree.cpp:2804
    #4 0x409f96 in main /root/pycdc/pycdc.cpp:28
    #5 0x7f6c04fb7b44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b44)
    #6 0x40d0e9 (/root/pycdc/build/pycdc+0x40d0e9)
```

With some test cases UBSan will say `/root/pycdc/pyc_object.h:15:54: runtime error: member access within null pointer of type 'const struct PycRef'`. I've encountered other issues as well like out of bounds reads, but upon minimizing those testcases they all seem rooted in this particular bug.

**Comment by rocky** [comment]
I suspect your bytecode is not well formed. The length of this is 4 bytes and there is no valid bytecode/wordcode of that size.

**Comment by geeknik** [comment]
But your software shouldn't crash when encountering malformed bytecode. Here is another example of a memory error that will only be visible if you build pycdc with ASAN  (heap-buffer-overflow):

 ./pycdc id\:000262\,sig\:06\,src\:000002\,op\:arith8\,pos\:442\,val\:+23
```
# Source Generated with Decompyle++
# File: id:000262,sig:06,src:000002,op:arith8,pos:442,val:+23 (Python 1.5)

'''
This is a doc string
'''

def Doc_Test():
    '''This has to be present'''
    pass


class XXX:

    def __init__(self):
        '''__init__: This has to be present'''
        self.a = 1

        def XXX22():
=================================================================
==24445==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60300000ca20 at pc 0x5511b2 bp 0x7ffcf573f6d0 sp 0x7ffcf573f6c8
READ of size 8 at 0x60300000ca20 thread T0
    #0 0x5511b1 in PycRef<ASTNode>::operator->() const /root/pycdc/pyc_object.h:53
    #1 0x5511b1 in decompyle(PycRef<PycCode>, PycModule*) /root/pycdc/ASTree.cpp:2812
    #2 0x56b03d in print_src(PycRef<ASTNode>, PycModule*) /root/pycdc/ASTree.cpp:2454
    #3 0x56d862 in print_src(PycRef<ASTNode>, PycModule*) /root/pycdc/ASTree.cpp:2662
    #4 0x56960a in print_src(PycRef<ASTNode>, PycModule*) /root/pycdc/ASTree.cpp:2388
    #5 0x548cb3 in decompyle(PycRef<PycCode>, PycModule*) /root/pycdc/ASTree.cpp:2876
    #6 0x56b03d in print_src(PycRef<ASTNode>, PycModule*) /root/pycdc/ASTree.cpp:2454
    #7 0x56d862 in print_src(PycRef<ASTNode>, PycModule*) /root/pycdc/ASTree.cpp:2662
    #8 0x56960a in print_src(PycRef<ASTNode>, PycModule*) /root/pycdc/ASTree.cpp:2388
    #9 0x548cb3 in decompyle(PycRef<PycCode>, PycModule*) /root/pycdc/ASTree.cpp:2876
    #10 0x56b03d in print_src(PycRef<ASTNode>, PycModule*) /root/pycdc/ASTree.cpp:2454
    #11 0x56f7b6 in print_src(PycRef<ASTNode>, PycModule*) /root/pycdc/ASTree.cpp:2688
    #12 0x56960a in print_src(PycRef<ASTNode>, PycModule*) /root/pycdc/ASTree.cpp:2388
    #13 0x548cb3 in decompyle(PycRef<PycCode>, PycModule*) /root/pycdc/ASTree.cpp:2876
    #14 0x409f96 in main /root/pycdc/pycdc.cpp:28
    #15 0x7f6817579b44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b44)
    #16 0x40d0e9 (/root/pycdc/build/pycdc+0x40d0e9)

0x60300000ca20 is located 0 bytes to the right of 32-byte region [0x60300000ca00,0x60300000ca20)
allocated by thread T0 here:
    #0 0x7f6818e40fff in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.1+0x54fff)
    #1 0x428b5a in BuildFromCode(PycRef<PycCode>, PycModule*) /root/pycdc/ASTree.cpp:2117
    #2 0x547606 in decompyle(PycRef<PycCode>, PycModule*) /root/pycdc/ASTree.cpp:2804
    #3 0x56b03d in print_src(PycRef<ASTNode>, PycModule*) /root/pycdc/ASTree.cpp:2454
    #4 0x56d862 in print_src(PycRef<ASTNode>, PycModule*) /root/pycdc/ASTree.cpp:2662
    #5 0x56960a in print_src(PycRef<ASTNode>, PycModule*) /root/pycdc/ASTree.cpp:2388
    #6 0x548cb3 in decompyle(PycRef<PycCode>, PycModule*) /root/pycdc/ASTree.cpp:2876
    #7 0x56b03d in print_src(PycRef<ASTNode>, PycModule*) /root/pycdc/ASTree.cpp:2454
    #8 0x56d862 in print_src(PycRef<ASTNode>, PycModule*) /root/pycdc/ASTree.cpp:2662
    #9 0x56960a in print_src(PycRef<ASTNode>, PycModule*) /root/pycdc/ASTree.cpp:2388
    #10 0x548cb3 in decompyle(PycRef<PycCode>, PycModule*) /root/pycdc/ASTree.cpp:2876
    #11 0x56b03d in print_src(PycRef<ASTNode>, PycModule*) /root/pycdc/ASTree.cpp:2454
    #12 0x56f7b6 in print_src(PycRef<ASTNode>, PycModule*) /root/pycdc/ASTree.cpp:2688
    #13 0x56960a in print_src(PycRef<ASTNode>, PycModule*) /root/pycdc/ASTree.cpp:2388
    #14 0x548cb3 in decompyle(PycRef<PycCode>, PycModule*) /root/pycdc/ASTree.cpp:2876
    #15 0x409f96 in main /root/pycdc/pycdc.cpp:28
    #16 0x7f6817579b44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b44)

SUMMARY: AddressSanitizer: heap-buffer-overflow /root/pycdc/pyc_object.h:53
```

**Comment by rocky** [comment]
> But ~your~ (from initial post) software shouldn't crash when encountering malformed bytecode

Ok. That's been addressed better https://github.com/rocky/python-xdis/commit/a21a3da2d1b504801b794f661908684a8ee19b31

Hey, judging by the activity here, it looks like things might get resolved faster if you'd suggest a fix or submit a merge request.

Also, although I don't know how this project deals with wandering issue reports, but in those I manage, I prefer one issue ticket, well per issue.
