### ISSUE TITLE
Got unsupported type 0x48 and Segmentation fault when invoking on a pytest .pyc

### ISSUE THREAD

**Issue by Lucas-C** [zrax/pycdc#57]
There is the error message:
```
$ /opt/pycdc/pycdc __pycache__/stupid_test.cpython-27-PYTEST.pyc 
CreateObject: Got unsupported type 0x48
# Source Generated with Decompyle++
# File: stupid_test.cpython-27-PYTEST.pyc (Python 2.7)

Segmentation fault
```

Any idea on what is causing it ?

**Comment by mancoast** [comment]
Upload the PYC file for further analysis.

**Comment by zjjott** [comment]
I meet Segmentation fault too.My IDE say this line is error:
```
fprintf(pyc_output, "%s = ", p->first.cast<ASTName>()->name()->value());
```
in `ASTree.cpp` ,line 2257

**Comment by kolsys** [comment]
```
#0  0x00007ffff71c8d71 in vfprintf () from /lib64/libc.so.6
#1  0x00007ffff71cedd7 in fprintf () from /lib64/libc.so.6
#2  0x0000000000444115 in print_src(PycRef<ASTNode>, PycModule*) ()
#3  0x0000000000448084 in print_src(PycRef<ASTNode>, PycModule*) ()
#4  0x0000000000444f72 in print_src(PycRef<ASTNode>, PycModule*) ()
#5  0x000000000044a356 in decompyle(PycRef<PycCode>, PycModule*) ()
#6  0x0000000000445891 in print_src(PycRef<ASTNode>, PycModule*) ()
#7  0x0000000000447390 in print_src(PycRef<ASTNode>, PycModule*) ()
#8  0x0000000000444f72 in print_src(PycRef<ASTNode>, PycModule*) ()
#9  0x000000000044a356 in decompyle(PycRef<PycCode>, PycModule*) ()
#10 0x0000000000445891 in print_src(PycRef<ASTNode>, PycModule*) ()
#11 0x00000000004477ac in print_src(PycRef<ASTNode>, PycModule*) ()
#12 0x0000000000444f72 in print_src(PycRef<ASTNode>, PycModule*) ()
#13 0x000000000044a356 in decompyle(PycRef<PycCode>, PycModule*) ()
#14 0x000000000042cb08 in main ()
```

https://dl.dropboxusercontent.com/u/62484523/preferences.pyc
